/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tci.importacao.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tci.importacao.bean.ConfigBean;

/**
 *
 * @author erick.nagano
 */
public class configView extends javax.swing.JFrame {

    ConfigBean configBean = new ConfigBean();

    /**
     * Creates new form configView
     */
    public configView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jTextField4 = new javax.swing.JTextField();
        buttonGroup4 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        usuarioText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        senhaText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        caminhocsvText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caminhologText = new javax.swing.JTextField();
        configdigitalizacaoText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        metaSelect = new javax.swing.JRadioButton();
        metaimgSelect = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        cabecalhosSelect = new javax.swing.JRadioButton();
        cabecalhonSelect = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        appendsSelect = new javax.swing.JRadioButton();
        appendnSelect = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        tipoarquivoText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        separadorText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tipodocumentoText = new javax.swing.JTextField();
        tipoprocessoText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        moduloentradaBox = new javax.swing.JComboBox();
        tipoenvioBox = new javax.swing.JComboBox();
        modulosaidaBox = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        idmoduloInt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nomecaixaText = new javax.swing.JTextField();
        nomeprotocoloText = new javax.swing.JTextField();
        nomeloteText = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        siarcosSelect = new javax.swing.JRadioButton();
        siarconSelect = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        urlwebserviceText = new javax.swing.JTextField();
        urlsiarcoText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        statusblockchainInt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        indicedocumentoText = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        campowebserviceText = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        numerocolunaInt = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        moduloprocessoBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1127, 662));
        setResizable(false);
        setSize(new java.awt.Dimension(1127, 662));

        panel.setBackground(new java.awt.Color(38, 56, 74));
        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setMaximumSize(new java.awt.Dimension(1127, 662));
        panel.setMinimumSize(new java.awt.Dimension(1127, 662));
        panel.setName(""); // NOI18N
        panel.setPreferredSize(new java.awt.Dimension(1127, 662));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioText.setBackground(new java.awt.Color(99, 99, 119));
        usuarioText.setForeground(new java.awt.Color(255, 255, 255));
        usuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextActionPerformed(evt);
            }
        });
        panel.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário :");
        jLabel1.setToolTipText("Infome o usuário do Webservice");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 20));

        senhaText.setBackground(new java.awt.Color(99, 99, 119));
        senhaText.setForeground(new java.awt.Color(255, 255, 255));
        senhaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextActionPerformed(evt);
            }
        });
        panel.add(senhaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha : ");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 51, 204));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN WEBSERVICE CONTENT");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Caminho : ");
        jLabel5.setToolTipText("");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, 20));

        caminhocsvText.setBackground(new java.awt.Color(99, 99, 119));
        caminhocsvText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(caminhocsvText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 190, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Caminho do arquivo LOG");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 260, -1));

        caminhologText.setBackground(new java.awt.Color(99, 99, 119));
        caminhologText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(caminhologText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 190, -1));

        configdigitalizacaoText.setBackground(new java.awt.Color(99, 99, 119));
        configdigitalizacaoText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(configdigitalizacaoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 190, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome da ConfigDigitalizacao");
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 260, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("URL do Webservice siarco");
        jLabel8.setToolTipText("");
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 280, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Indice do documento : ");
        panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Metadados");
        panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 70, -1));

        metaSelect.setBackground(new java.awt.Color(38, 56, 74));
        metaSelect.setForeground(new java.awt.Color(255, 255, 255));
        metaSelect.setText("Metadados");
        panel.add(metaSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        metaimgSelect.setBackground(new java.awt.Color(38, 56, 74));
        metaimgSelect.setForeground(new java.awt.Color(255, 255, 255));
        metaimgSelect.setText("Metadados com imagem");
        metaimgSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metaimgSelectActionPerformed(evt);
            }
        });
        panel.add(metaimgSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 180, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cabeçalho");
        panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        cabecalhosSelect.setBackground(new java.awt.Color(38, 56, 74));
        cabecalhosSelect.setForeground(new java.awt.Color(255, 255, 255));
        cabecalhosSelect.setText("Sim");
        panel.add(cabecalhosSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        cabecalhonSelect.setBackground(new java.awt.Color(38, 56, 74));
        cabecalhonSelect.setForeground(new java.awt.Color(255, 255, 255));
        cabecalhonSelect.setText("Não");
        cabecalhonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabecalhonSelectActionPerformed(evt);
            }
        });
        panel.add(cabecalhonSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Append de arquivo");
        panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 230, -1));

        appendsSelect.setBackground(new java.awt.Color(38, 56, 74));
        appendsSelect.setForeground(new java.awt.Color(255, 255, 255));
        appendsSelect.setText("Sim");
        panel.add(appendsSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        appendnSelect.setBackground(new java.awt.Color(38, 56, 74));
        appendnSelect.setForeground(new java.awt.Color(255, 255, 255));
        appendnSelect.setText("Não");
        appendnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendnSelectActionPerformed(evt);
            }
        });
        panel.add(appendnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tipo arquivo : ");
        panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 20));

        tipoarquivoText.setBackground(new java.awt.Color(99, 99, 119));
        tipoarquivoText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(tipoarquivoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CSV");
        panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Separador : ");
        panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 20));

        separadorText.setBackground(new java.awt.Color(99, 99, 119));
        separadorText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(separadorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 190, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nome do tipo documento : ");
        panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 160, 20));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nome do tipo processo : ");
        panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, 20));

        tipodocumentoText.setBackground(new java.awt.Color(99, 99, 119));
        tipodocumentoText.setForeground(new java.awt.Color(255, 255, 255));
        tipodocumentoText.setToolTipText("Colocar separador entre os indices");
        panel.add(tipodocumentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 190, -1));

        tipoprocessoText.setBackground(new java.awt.Color(99, 99, 119));
        tipoprocessoText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(tipoprocessoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 190, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Modulo de entrada");
        panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, -1, 20));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Modulo de saida");
        panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, 20));

        moduloentradaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Webcervice" }));
        moduloentradaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloentradaBoxActionPerformed(evt);
            }
        });
        panel.add(moduloentradaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 100, -1));

        tipoenvioBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Imagem", "Jucec" }));
        tipoenvioBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoenvioBoxActionPerformed(evt);
            }
        });
        panel.add(tipoenvioBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 90, -1));

        modulosaidaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione ...", "CQ", "Indexer", "OCR", "Content" }));
        modulosaidaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulosaidaBoxActionPerformed(evt);
            }
        });
        panel.add(modulosaidaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, 100, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Modulo do processo");
        panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, 20));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ID Modulo do processo");
        panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 200, 20));

        idmoduloInt.setBackground(new java.awt.Color(99, 99, 119));
        idmoduloInt.setForeground(new java.awt.Color(255, 255, 255));
        idmoduloInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmoduloIntActionPerformed(evt);
            }
        });
        panel.add(idmoduloInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 200, 30, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("DEFINIR NOME DO DOCUMENTO");
        panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 220, 20));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Caixa");
        panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Protocolo");
        panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 100, 20));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Lote");
        panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 40, 20));

        nomecaixaText.setBackground(new java.awt.Color(99, 99, 119));
        nomecaixaText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(nomecaixaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 120, -1));

        nomeprotocoloText.setBackground(new java.awt.Color(99, 99, 119));
        nomeprotocoloText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(nomeprotocoloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 120, -1));

        nomeloteText.setBackground(new java.awt.Color(99, 99, 119));
        nomeloteText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(nomeloteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 120, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Webservice siarco");
        panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 280, -1));

        siarcosSelect.setBackground(new java.awt.Color(38, 56, 74));
        siarcosSelect.setForeground(new java.awt.Color(255, 255, 255));
        siarcosSelect.setText("Sim");
        panel.add(siarcosSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));

        siarconSelect.setBackground(new java.awt.Color(38, 56, 74));
        siarconSelect.setForeground(new java.awt.Color(255, 255, 255));
        siarconSelect.setText("Não");
        panel.add(siarconSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("URL do Webservice");
        jLabel28.setToolTipText("");
        panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 260, -1));

        urlwebserviceText.setBackground(new java.awt.Color(99, 99, 119));
        urlwebserviceText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(urlwebserviceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 190, -1));

        urlsiarcoText.setBackground(new java.awt.Color(99, 99, 119));
        urlsiarcoText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(urlsiarcoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 190, -1));
        panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 340, 0));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Numero de coluna no arquivo");
        panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, 20));

        statusblockchainInt.setBackground(new java.awt.Color(99, 99, 119));
        statusblockchainInt.setForeground(new java.awt.Color(255, 255, 255));
        statusblockchainInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusblockchainIntActionPerformed(evt);
            }
        });
        panel.add(statusblockchainInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 20, -1));
        panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, -1, -1));
        panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 190, -1));

        indicedocumentoText.setBackground(new java.awt.Color(99, 99, 119));
        indicedocumentoText.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(indicedocumentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 190, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Campos do Webservice");
        panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 280, -1));

        campowebserviceText.setBackground(new java.awt.Color(99, 99, 119));
        campowebserviceText.setForeground(new java.awt.Color(255, 255, 255));
        campowebserviceText.setToolTipText("Mais de um campo deverão ser separados por - \"traço\"");
        campowebserviceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campowebserviceTextActionPerformed(evt);
            }
        });
        panel.add(campowebserviceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 190, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Insere status na coluna blockChain");
        panel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 200, 20));

        numerocolunaInt.setBackground(new java.awt.Color(99, 99, 119));
        numerocolunaInt.setForeground(new java.awt.Color(255, 255, 255));
        numerocolunaInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerocolunaIntActionPerformed(evt);
            }
        });
        panel.add(numerocolunaInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 20, -1));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Tipo de envio");
        panel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 130, 20));

        moduloprocessoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione ...", "CQ", "Indexer", "OCR", "Content" }));
        moduloprocessoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloprocessoBoxActionPerformed(evt);
            }
        });
        panel.add(moduloprocessoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 100, -1));

        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextActionPerformed

    }//GEN-LAST:event_senhaTextActionPerformed

    private void moduloentradaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloentradaBoxActionPerformed

        configBean.setModuloentradaBox(moduloentradaBox.getSelectedItem().toString());

    }//GEN-LAST:event_moduloentradaBoxActionPerformed

    private void tipoenvioBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoenvioBoxActionPerformed

        configBean.setTipodenvioBox(tipoenvioBox.getSelectedItem().toString());

    }//GEN-LAST:event_tipoenvioBoxActionPerformed

    private void modulosaidaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulosaidaBoxActionPerformed

        configBean.setModulosaidaBox(modulosaidaBox.getSelectedItem().toString());


    }//GEN-LAST:event_modulosaidaBoxActionPerformed

    private void cabecalhonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabecalhonSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cabecalhonSelectActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void moduloprocessoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloprocessoBoxActionPerformed
        
        configBean.setModuloprocessoBox(moduloprocessoBox.getSelectedItem().toString());
        
    }//GEN-LAST:event_moduloprocessoBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (usuarioText.getText() == null || usuarioText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar usuário !");
            return;

        } else {

            configBean.setUsuarioText(usuarioText.getText());
        }

        if (senhaText.getText() == null || senhaText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar senha !");
            return;

        } else {

            configBean.setSenhaText(senhaText.getText());
        }

        if (caminhocsvText.getText() == null || caminhocsvText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar caminho do CSV !");
            return;

        } else {

            configBean.setCaminhocsvText(caminhocsvText.getText());

        }

        if (tipoarquivoText.getText() == null || tipoarquivoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o tipo de arquivo !");
            return;

        } else {

            configBean.setTipoarquivoText(tipoarquivoText.getText());

        }

        if (separadorText.getText() == null || separadorText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar separador !");
            return;

        } else {

            configBean.setSeparadorText(separadorText.getText());

        }

        if (caminhologText.getText() == null || caminhologText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar caminho do log que será salvo !");
            return;

        } else {

            configBean.setCaminhologText(caminhologText.getText());

        }

        if (configdigitalizacaoText.getText() == null || configdigitalizacaoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar a config digitalização  !");
            return;

        } else {

            configBean.setConfigdigitalizacaoText(configdigitalizacaoText.getText());

        }

        if (urlwebserviceText.getText() == null || urlwebserviceText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar a url do webservice !");
            return;

        } else {

            configBean.setUrlwebserviceText(urlwebserviceText.getText());

        }

        if (tipoprocessoText.getText() == null || tipoprocessoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o tipo de processo !");
            return;
        } else {

            configBean.setTipoprocessoText(tipoprocessoText.getText());

        }

        if (tipodocumentoText.getText() == null || tipodocumentoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o tipo documento !");
            return;
        } else {

            configBean.setTipodocumentoText(tipodocumentoText.getText());

        }

        if (nomecaixaText.getText() == null || nomecaixaText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o nome da caixa !");
            return;
        } else {

            configBean.setNomecaixaText(nomecaixaText.getText());

        }

        if (nomeprotocoloText.getText() == null || nomeprotocoloText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o nome protocolo !");
            return;
        } else {

            configBean.setNomeprotocoloText(nomeprotocoloText.getText());

        }

        if (nomeloteText.getText() == null || nomeloteText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o nome do lote !");
            return;
        } else {

            configBean.setNomeloteText(nomeloteText.getText());

        }

        if (numerocolunaInt.getText() == null || numerocolunaInt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o numero de coluna  !");
            return;
        } else {

            configBean.setNumerocolunaInt(Integer.valueOf(numerocolunaInt.getText()));

        }

        if (statusblockchainInt.getText() == null || statusblockchainInt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o status do block chain  !");
            return;
        } else {

            configBean.setStatusblockchainInt(Integer.valueOf(statusblockchainInt.getText()));

        }

        if (campowebserviceText.getText() == null || campowebserviceText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar os campos do webservice  !");
            return;
        } else {

            configBean.setCampowebserviceText(campowebserviceText.getText());

        }

        if (appendsSelect.isSelected() == true) {

            configBean.setAppendsSelect(appendsSelect.isSelected());

        } else {

            configBean.setMetaSelect(metaSelect.isSelected());

        }

        if (metaSelect.isSelected() == true) {

            configBean.setMetaSelect(metaSelect.isSelected());

        } else {

            configBean.setMetaimgSelect(metaimgSelect.isSelected());

        }

        if (cabecalhosSelect.isSelected() == true) {

            configBean.setMetaSelect(cabecalhosSelect.isSelected());

        } else {

            configBean.setCabecalhonSelect(cabecalhosSelect.isSelected());

        }

        if (moduloentradaBox.getSelectedItem().equals("Selecione ...")) {

            //Selecione ..., CQ, Indexer, OCR, Content
            JOptionPane.showMessageDialog(null, "Selecione o modulo do entrada !");
            return;

        }

        if (modulosaidaBox.getSelectedItem().equals("Selecione ...")) {

            //Selecione ..., CQ, Indexer, OCR, Content
            JOptionPane.showMessageDialog(null, "Selecione o modulo de saida !");
            return;

        }

        if (moduloprocessoBox.getSelectedItem().equals("Selecione ...")) {

            //Selecione ..., CQ, Indexer, OCR, Content
            JOptionPane.showMessageDialog(null, "Selecione o modulo do processo !");
            return;

        }
        if (idmoduloInt.getText() == null || idmoduloInt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o ID modulo do processo  !");
            return;
        } else {

            configBean.setIdmoduloInt(Integer.valueOf(idmoduloInt.getText()));

        }
        
        if (siarcosSelect.isSelected() == true ){
            
            configBean.setSiarcosSelect(siarcosSelect.isSelected());
            
        }else {
            
            configBean.setSiarconSelect(siarconSelect.isSelected());
            
        }
        
        if (urlsiarcoText.getText() == null || urlsiarcoText.getText().equals ("")){
            
            JOptionPane.showMessageDialog(null, "Informar a url do webservice siarco  !");
            
        }else{
            
            configBean.setUrlsiarcoText(urlsiarcoText.getText());
            
        }
        
      

    }//GEN-LAST:event_jButton1ActionPerformed


    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed

    }//GEN-LAST:event_usuarioTextActionPerformed

    private void campowebserviceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campowebserviceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campowebserviceTextActionPerformed

    private void numerocolunaIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerocolunaIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerocolunaIntActionPerformed

    private void statusblockchainIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusblockchainIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusblockchainIntActionPerformed

    private void appendnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendnSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appendnSelectActionPerformed

    private void metaimgSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metaimgSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metaimgSelectActionPerformed

    private void idmoduloIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmoduloIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idmoduloIntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(configView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(configView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(configView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(configView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new configView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton appendnSelect;
    private javax.swing.JRadioButton appendsSelect;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton cabecalhonSelect;
    private javax.swing.JRadioButton cabecalhosSelect;
    private javax.swing.JTextField caminhocsvText;
    private javax.swing.JTextField caminhologText;
    private javax.swing.JTextField campowebserviceText;
    private javax.swing.JTextField configdigitalizacaoText;
    private javax.swing.JTextField idmoduloInt;
    private javax.swing.JTextField indicedocumentoText;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton metaSelect;
    private javax.swing.JRadioButton metaimgSelect;
    private javax.swing.JComboBox moduloentradaBox;
    private javax.swing.JComboBox moduloprocessoBox;
    private javax.swing.JComboBox modulosaidaBox;
    private javax.swing.JTextField nomecaixaText;
    private javax.swing.JTextField nomeloteText;
    private javax.swing.JTextField nomeprotocoloText;
    private javax.swing.JTextField numerocolunaInt;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField senhaText;
    private javax.swing.JTextField separadorText;
    private javax.swing.JRadioButton siarconSelect;
    private javax.swing.JRadioButton siarcosSelect;
    private javax.swing.JTextField statusblockchainInt;
    private javax.swing.JTextField tipoarquivoText;
    private javax.swing.JTextField tipodocumentoText;
    private javax.swing.JComboBox tipoenvioBox;
    private javax.swing.JTextField tipoprocessoText;
    private javax.swing.JTextField urlsiarcoText;
    private javax.swing.JTextField urlwebserviceText;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
