/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tci.importacao.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author erick.nagano
 */
public class configView extends javax.swing.JFrame {

    /**
     * Creates new form configView
     */
    public configView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jTextField4 = new javax.swing.JTextField();
        tipoenvioBox = new javax.swing.JPanel();
        usuarioText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        senhaText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        caminhocsvText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caminhologText = new javax.swing.JTextField();
        configdigitalizacaoText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        tipoarquivoText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        separadorText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tipodocumentoText = new javax.swing.JTextField();
        tipoprocessoText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        moduloentradaBox = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        modulosaidaBox = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        idmoduloInt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nomecaixaText = new javax.swing.JTextField();
        nomeprotocoloText = new javax.swing.JTextField();
        nomeloteText = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        urlwebserviceText1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        statusblockchainInt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        indicedocumentoText = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        campowebserviceText = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        numerocolunaInt = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        moduloprocessoBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1127, 662));
        setResizable(false);
        setSize(new java.awt.Dimension(1127, 662));

        tipoenvioBox.setBackground(new java.awt.Color(38, 56, 74));
        tipoenvioBox.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.setMaximumSize(new java.awt.Dimension(1127, 662));
        tipoenvioBox.setMinimumSize(new java.awt.Dimension(1127, 662));
        tipoenvioBox.setName(""); // NOI18N
        tipoenvioBox.setPreferredSize(new java.awt.Dimension(1127, 662));
        tipoenvioBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioText.setBackground(new java.awt.Color(99, 99, 119));
        usuarioText.setForeground(new java.awt.Color(255, 255, 255));
        usuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextActionPerformed(evt);
            }
        });
        tipoenvioBox.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário :");
        jLabel1.setToolTipText("Infome o usuário do Webservice");
        tipoenvioBox.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 20));

        senhaText.setBackground(new java.awt.Color(99, 99, 119));
        senhaText.setForeground(new java.awt.Color(255, 255, 255));
        senhaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextActionPerformed(evt);
            }
        });
        tipoenvioBox.add(senhaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha : ");
        tipoenvioBox.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));
        tipoenvioBox.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 51, 204));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN WEBSERVICE CONTENT");
        tipoenvioBox.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Caminho : ");
        jLabel5.setToolTipText("");
        tipoenvioBox.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, 20));

        caminhocsvText.setBackground(new java.awt.Color(99, 99, 119));
        caminhocsvText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(caminhocsvText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 190, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Caminho do arquivo LOG");
        tipoenvioBox.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 260, -1));

        caminhologText.setBackground(new java.awt.Color(99, 99, 119));
        caminhologText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(caminhologText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 190, -1));

        configdigitalizacaoText.setBackground(new java.awt.Color(99, 99, 119));
        configdigitalizacaoText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(configdigitalizacaoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 190, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome da ConfigDigitalizacao");
        tipoenvioBox.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 260, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("URL do Webservice siarco");
        jLabel8.setToolTipText("");
        tipoenvioBox.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 280, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Indice do documento : ");
        tipoenvioBox.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Metadados");
        tipoenvioBox.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 70, -1));

        jRadioButton1.setBackground(new java.awt.Color(38, 56, 74));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Metadados");
        tipoenvioBox.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(38, 56, 74));
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Metadados com imagem");
        tipoenvioBox.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 180, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cabeçalho");
        tipoenvioBox.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(38, 56, 74));
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Sim");
        tipoenvioBox.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(38, 56, 74));
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Não");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        tipoenvioBox.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Append de arquivo");
        tipoenvioBox.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 230, -1));

        jRadioButton5.setBackground(new java.awt.Color(38, 56, 74));
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Sim");
        tipoenvioBox.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jRadioButton6.setBackground(new java.awt.Color(38, 56, 74));
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Não");
        tipoenvioBox.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tipo arquivo : ");
        tipoenvioBox.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 20));

        tipoarquivoText.setBackground(new java.awt.Color(99, 99, 119));
        tipoarquivoText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(tipoarquivoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CSV");
        tipoenvioBox.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Separador : ");
        tipoenvioBox.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 20));

        separadorText.setBackground(new java.awt.Color(99, 99, 119));
        separadorText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(separadorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 190, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nome do tipo documento : ");
        tipoenvioBox.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 150, 20));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nome do tipo processo : ");
        tipoenvioBox.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 20));

        tipodocumentoText.setBackground(new java.awt.Color(99, 99, 119));
        tipodocumentoText.setForeground(new java.awt.Color(255, 255, 255));
        tipodocumentoText.setToolTipText("Colocar separador entre os indices");
        tipoenvioBox.add(tipodocumentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 190, -1));

        tipoprocessoText.setBackground(new java.awt.Color(99, 99, 119));
        tipoprocessoText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(tipoprocessoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 190, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Modulo de entrada");
        tipoenvioBox.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, -1, 20));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Modulo de saida");
        tipoenvioBox.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, 20));

        moduloentradaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Webcervice" }));
        moduloentradaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloentradaBoxActionPerformed(evt);
            }
        });
        tipoenvioBox.add(moduloentradaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 90, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Imagem", "Jucec" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        tipoenvioBox.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 90, -1));

        modulosaidaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione ...", "CQ", "Indexer", "OCR", "Content" }));
        modulosaidaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulosaidaBoxActionPerformed(evt);
            }
        });
        tipoenvioBox.add(modulosaidaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, 90, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Modulo do processo");
        tipoenvioBox.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, 20));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ID Modulo do processo");
        tipoenvioBox.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 200, 20));

        idmoduloInt.setBackground(new java.awt.Color(99, 99, 119));
        idmoduloInt.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(idmoduloInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, 20, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("DEFINIR NOME DO DOCUMENTO");
        tipoenvioBox.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 220, 20));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Caixa");
        tipoenvioBox.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Protocolo");
        tipoenvioBox.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 100, 20));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Lote");
        tipoenvioBox.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 40, 20));

        nomecaixaText.setBackground(new java.awt.Color(99, 99, 119));
        nomecaixaText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(nomecaixaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 120, -1));

        nomeprotocoloText.setBackground(new java.awt.Color(99, 99, 119));
        nomeprotocoloText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(nomeprotocoloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 120, -1));

        nomeloteText.setBackground(new java.awt.Color(99, 99, 119));
        nomeloteText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(nomeloteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 120, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Webservice siarco");
        tipoenvioBox.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 280, -1));

        jRadioButton7.setBackground(new java.awt.Color(38, 56, 74));
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Sim");
        tipoenvioBox.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));

        jRadioButton8.setBackground(new java.awt.Color(38, 56, 74));
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Não");
        tipoenvioBox.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("URL do Webservice");
        jLabel28.setToolTipText("");
        tipoenvioBox.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 260, -1));

        urlwebserviceText1.setBackground(new java.awt.Color(99, 99, 119));
        urlwebserviceText1.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(urlwebserviceText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 190, -1));

        jTextField1.setBackground(new java.awt.Color(99, 99, 119));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 190, -1));
        tipoenvioBox.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 340, 0));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Numero de coluna no arquivo");
        tipoenvioBox.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, 20));

        statusblockchainInt.setBackground(new java.awt.Color(99, 99, 119));
        statusblockchainInt.setForeground(new java.awt.Color(255, 255, 255));
        statusblockchainInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusblockchainIntActionPerformed(evt);
            }
        });
        tipoenvioBox.add(statusblockchainInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 20, -1));
        tipoenvioBox.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, -1, -1));
        tipoenvioBox.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 190, -1));

        indicedocumentoText.setBackground(new java.awt.Color(99, 99, 119));
        indicedocumentoText.setForeground(new java.awt.Color(255, 255, 255));
        tipoenvioBox.add(indicedocumentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 190, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Campos do Webservice");
        tipoenvioBox.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 280, -1));

        campowebserviceText.setBackground(new java.awt.Color(99, 99, 119));
        campowebserviceText.setForeground(new java.awt.Color(255, 255, 255));
        campowebserviceText.setToolTipText("Mais de um campo deverão ser separados por - \"traço\"");
        campowebserviceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campowebserviceTextActionPerformed(evt);
            }
        });
        tipoenvioBox.add(campowebserviceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 190, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Insere status na coluna blockChain");
        tipoenvioBox.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 200, 20));

        numerocolunaInt.setBackground(new java.awt.Color(99, 99, 119));
        numerocolunaInt.setForeground(new java.awt.Color(255, 255, 255));
        numerocolunaInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerocolunaIntActionPerformed(evt);
            }
        });
        tipoenvioBox.add(numerocolunaInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 20, -1));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Tipo de envio");
        tipoenvioBox.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 130, 20));

        moduloprocessoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione ...", "CQ", "Indexer", "OCR", "Content" }));
        moduloprocessoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloprocessoBoxActionPerformed(evt);
            }
        });
        tipoenvioBox.add(moduloprocessoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 90, -1));

        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tipoenvioBox.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tipoenvioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tipoenvioBox, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextActionPerformed
        
    }//GEN-LAST:event_senhaTextActionPerformed

    private void moduloentradaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloentradaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduloentradaBoxActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void modulosaidaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulosaidaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modulosaidaBoxActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void moduloprocessoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloprocessoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduloprocessoBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (usuarioText.getText() == null || usuarioText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar usuário !");
            return;
        } else {
            if (senhaText.getText() == null || senhaText.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informar senha !");
                return;
            } else {
                if (caminhocsvText.getText() == null || caminhocsvText.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informar caminho do CSV !");
                    return;
                } else {
                    if (tipoarquivoText.getText() == null || tipoarquivoText.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Informar o tipo de arquivo !");
                        return;
                    } else {    
                        if (separadorText.getText() == null || separadorText.getText().equals("")) {
                            JOptionPane.showMessageDialog(null, "Informar separador !");
                            return;
                        } else {
                            if (caminhologText.getText() == null || caminhologText.getText().equals("")) {
                                JOptionPane.showMessageDialog(null, "Informar caminho do log que será salvo !");
                                return;
                            } else {
                                if (configdigitalizacaoText.getText() == null || configdigitalizacaoText.getText().equals("")) {
                                    JOptionPane.showMessageDialog(null, "Informar a config digitalização  !");
                                    return;
                                } else {
                                    if (urlwebserviceText1.getText() == null || urlwebserviceText1.getText().equals("")) {
                                        JOptionPane.showMessageDialog(null, "Informar a url do webservice !");
                                        return;
                                    } else {
                                        if (urlwebserviceText1.getText() == null || urlwebserviceText1.getText().equals("")) {
                                            JOptionPane.showMessageDialog(null, "Informar a url do webservice !");
                                            return;
                                        } else {
                                            if (tipoprocessoText.getText() == null || tipoprocessoText.getText().equals("")) {
                                                JOptionPane.showMessageDialog(null, "Informar o tipo de processo !");
                                                return;
                                            } else {
                                                if (tipodocumentoText.getText() == null || tipodocumentoText.getText().equals("")) {
                                                    JOptionPane.showMessageDialog(null, "Informar o tipo documento !");
                                                    return;
                                                } else {
                                                    if (nomecaixaText.getText() == null || nomecaixaText.getText().equals("")) {
                                                        JOptionPane.showMessageDialog(null, "Informar o nome da caixa !");
                                                        return;
                                                    } else {
                                                        if (nomeprotocoloText.getText() == null || nomeprotocoloText.getText().equals("")) {
                                                            JOptionPane.showMessageDialog(null, "Informar o nome protocolo !");
                                                            return;
                                                        } else {
                                                            if (nomeloteText.getText() == null || nomeloteText.getText().equals("")) {
                                                                JOptionPane.showMessageDialog(null, "Informar o nome do lote !");
                                                                return;
                                                            } else {
                                                                if (numerocolunaInt.getText() == null || numerocolunaInt.getText().equals("")) {
                                                                    JOptionPane.showMessageDialog(null, "Informar o numero de coluna  !");
                                                                    return;
                                                                } else {
                                                                    if (statusblockchainInt.getText() == null || statusblockchainInt.getText().equals("")) {
                                                                        JOptionPane.showMessageDialog(null, "Informar o status do block chain  !");
                                                                        return;
                                                                    } else {
                                                                        if (campowebserviceText.getText() == null || campowebserviceText.getText().equals("")) {
                                                                            JOptionPane.showMessageDialog(null, "Informar os campos do webservice  !");
                                                                            return;
                                                                        } else {
                                                                             if (campowebserviceText.getText() == null || campowebserviceText.getText().equals("")) {
                                                                            JOptionPane.showMessageDialog(null, "Informar os campos do webservice  !");
                                                                            return;
                                                                             }else {
                                                                                 if (modulosaidaBox.getSelectedItem().equals("Selecione ...")){
                                                                                     JOptionPane.showMessageDialog(null, "Selecione uma opção !");
                                                                                 }else {
                                                                                     if (moduloentradaBox.getSelectedItem().equals("Selecione ...")){
                                                                                     JOptionPane.showMessageDialog(null, "Selecione uma opção !");
                                                                                 }else {
                                                                                         
                                                                                     }
                                                                                         
                                                                             }
                                                                            
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
                                                            
                                                        
                                                        
    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed

    }//GEN-LAST:event_usuarioTextActionPerformed

    private void campowebserviceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campowebserviceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campowebserviceTextActionPerformed

    private void numerocolunaIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerocolunaIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerocolunaIntActionPerformed

    private void statusblockchainIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusblockchainIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusblockchainIntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(configView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(configView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(configView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(configView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new configView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField caminhocsvText;
    private javax.swing.JTextField caminhologText;
    private javax.swing.JTextField campowebserviceText;
    private javax.swing.JTextField configdigitalizacaoText;
    private javax.swing.JTextField idmoduloInt;
    private javax.swing.JTextField indicedocumentoText;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox moduloentradaBox;
    private javax.swing.JComboBox moduloprocessoBox;
    private javax.swing.JComboBox modulosaidaBox;
    private javax.swing.JTextField nomecaixaText;
    private javax.swing.JTextField nomeloteText;
    private javax.swing.JTextField nomeprotocoloText;
    private javax.swing.JTextField numerocolunaInt;
    private javax.swing.JTextField senhaText;
    private javax.swing.JTextField separadorText;
    private javax.swing.JTextField statusblockchainInt;
    private javax.swing.JTextField tipoarquivoText;
    private javax.swing.JTextField tipodocumentoText;
    private javax.swing.JPanel tipoenvioBox;
    private javax.swing.JTextField tipoprocessoText;
    private javax.swing.JTextField urlwebserviceText1;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
