/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tci.importacao.view;

import javax.swing.JOptionPane;
import tci.importacao.bean.ConfigBean;
import tci.importacao.properties.PropertiesCsv;

/**
 *
 * @author erick.nagano
 */
public class ImportacaoImagemIndice extends javax.swing.JFrame {

    private String strProperties;

    /**
     * Creates new form ImportacaoImagemIndice
     */
    public ImportacaoImagemIndice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        usuarioText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        senhaText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caminhologText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        configdigitalizacaoText = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        urlwebserviceText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        appendnSelect = new javax.swing.JRadioButton();
        appendsSelect = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        usuarioText1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        senhaText1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        caminhologText1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        configdigitalizacaoText1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        urlwebserviceText1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        appendnSelect1 = new javax.swing.JRadioButton();
        appendsSelect1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        metaSelect = new javax.swing.JRadioButton();
        metaimgSelect = new javax.swing.JRadioButton();
        statusblockchainInt = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        campowebserviceText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        moduloentradaBox = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        modulosaidaBox = new javax.swing.JComboBox();
        moduloprocessoBox = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        idmoduloInt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        siarcosSelect = new javax.swing.JRadioButton();
        siarconSelect = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        urlsiarcoText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();

        jLabel4.setBackground(new java.awt.Color(255, 51, 204));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN WEBSERVICE CONTENT");

        usuarioText.setBackground(new java.awt.Color(99, 99, 119));
        usuarioText.setForeground(new java.awt.Color(255, 255, 255));
        usuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário :");
        jLabel1.setToolTipText("Infome o usuário do Webservice");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha : ");

        senhaText.setBackground(new java.awt.Color(99, 99, 119));
        senhaText.setForeground(new java.awt.Color(255, 255, 255));
        senhaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Caminho do arquivo LOG");

        caminhologText.setBackground(new java.awt.Color(99, 99, 119));
        caminhologText.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome da ConfigDigitalizacao");

        configdigitalizacaoText.setBackground(new java.awt.Color(99, 99, 119));
        configdigitalizacaoText.setForeground(new java.awt.Color(255, 255, 255));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("URL do Webservice");
        jLabel28.setToolTipText("");

        urlwebserviceText.setBackground(new java.awt.Color(99, 99, 119));
        urlwebserviceText.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Append de arquivo");

        appendnSelect.setBackground(new java.awt.Color(38, 56, 74));
        appendnSelect.setForeground(new java.awt.Color(255, 255, 255));
        appendnSelect.setText("Não");
        appendnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendnSelectActionPerformed(evt);
            }
        });

        appendsSelect.setBackground(new java.awt.Color(38, 56, 74));
        appendsSelect.setForeground(new java.awt.Color(255, 255, 255));
        appendsSelect.setText("Sim");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(38, 56, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 51, 204));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOGIN WEBSERVICE CONTENT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 20));

        usuarioText1.setBackground(new java.awt.Color(99, 99, 119));
        usuarioText1.setForeground(new java.awt.Color(255, 255, 255));
        usuarioText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioText1ActionPerformed(evt);
            }
        });
        jPanel1.add(usuarioText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuário :");
        jLabel3.setToolTipText("Infome o usuário do Webservice");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Senha : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        senhaText1.setBackground(new java.awt.Color(99, 99, 119));
        senhaText1.setForeground(new java.awt.Color(255, 255, 255));
        senhaText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaText1ActionPerformed(evt);
            }
        });
        jPanel1.add(senhaText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Caminho do arquivo LOG");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, -1));

        caminhologText1.setBackground(new java.awt.Color(99, 99, 119));
        caminhologText1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(caminhologText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 190, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nome da ConfigDigitalizacao");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 260, -1));

        configdigitalizacaoText1.setBackground(new java.awt.Color(99, 99, 119));
        configdigitalizacaoText1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(configdigitalizacaoText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 190, -1));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("URL do Webservice");
        jLabel29.setToolTipText("");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, -1));

        urlwebserviceText1.setBackground(new java.awt.Color(99, 99, 119));
        urlwebserviceText1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(urlwebserviceText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 190, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Append de arquivo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 230, -1));

        appendnSelect1.setBackground(new java.awt.Color(38, 56, 74));
        appendnSelect1.setForeground(new java.awt.Color(255, 255, 255));
        appendnSelect1.setText("Não");
        appendnSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendnSelect1ActionPerformed(evt);
            }
        });
        jPanel1.add(appendnSelect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        appendsSelect1.setBackground(new java.awt.Color(38, 56, 74));
        appendsSelect1.setForeground(new java.awt.Color(255, 255, 255));
        appendsSelect1.setText("Sim");
        jPanel1.add(appendsSelect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Metadados");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 70, -1));

        metaSelect.setBackground(new java.awt.Color(38, 56, 74));
        metaSelect.setForeground(new java.awt.Color(255, 255, 255));
        metaSelect.setText("Metadados");
        jPanel1.add(metaSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        metaimgSelect.setBackground(new java.awt.Color(38, 56, 74));
        metaimgSelect.setForeground(new java.awt.Color(255, 255, 255));
        metaimgSelect.setText("Metadados com imagem");
        metaimgSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metaimgSelectActionPerformed(evt);
            }
        });
        jPanel1.add(metaimgSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 180, -1));

        statusblockchainInt.setBackground(new java.awt.Color(99, 99, 119));
        statusblockchainInt.setForeground(new java.awt.Color(255, 255, 255));
        statusblockchainInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusblockchainIntActionPerformed(evt);
            }
        });
        jPanel1.add(statusblockchainInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 40, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Campos do Webservice");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 280, -1));

        campowebserviceText.setBackground(new java.awt.Color(99, 99, 119));
        campowebserviceText.setForeground(new java.awt.Color(255, 255, 255));
        campowebserviceText.setToolTipText("Mais de um campo deverão ser separados por - \"traço\"");
        campowebserviceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campowebserviceTextActionPerformed(evt);
            }
        });
        jPanel1.add(campowebserviceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 190, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Modulo de entrada");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, 20));

        moduloentradaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Webcervice" }));
        moduloentradaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloentradaBoxActionPerformed(evt);
            }
        });
        jPanel1.add(moduloentradaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 100, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Modulo de saida");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, 20));

        modulosaidaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione ...", "CQ", "Indexer", "OCR", "Content" }));
        modulosaidaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulosaidaBoxActionPerformed(evt);
            }
        });
        jPanel1.add(modulosaidaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 100, -1));

        moduloprocessoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione ...", "CQ", "Indexer", "OCR", "Content" }));
        moduloprocessoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloprocessoBoxActionPerformed(evt);
            }
        });
        jPanel1.add(moduloprocessoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 100, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ID Modulo do processo");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 200, 20));

        idmoduloInt.setBackground(new java.awt.Color(99, 99, 119));
        idmoduloInt.setForeground(new java.awt.Color(255, 255, 255));
        idmoduloInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmoduloIntActionPerformed(evt);
            }
        });
        jPanel1.add(idmoduloInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 100, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Modulo do processo");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Webservice siarco");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 280, -1));

        siarcosSelect.setBackground(new java.awt.Color(38, 56, 74));
        siarcosSelect.setForeground(new java.awt.Color(255, 255, 255));
        siarcosSelect.setText("Sim");
        jPanel1.add(siarcosSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        siarconSelect.setBackground(new java.awt.Color(38, 56, 74));
        siarconSelect.setForeground(new java.awt.Color(255, 255, 255));
        siarconSelect.setText("Não");
        jPanel1.add(siarconSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("URL do Webservice siarco");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 280, -1));

        urlsiarcoText.setBackground(new java.awt.Color(99, 99, 119));
        urlsiarcoText.setForeground(new java.awt.Color(255, 255, 255));
        urlsiarcoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlsiarcoTextActionPerformed(evt);
            }
        });
        jPanel1.add(urlsiarcoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 190, -1));

        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Insere status na coluna blockChain");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed

    }//GEN-LAST:event_usuarioTextActionPerformed

    private void senhaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextActionPerformed

    }//GEN-LAST:event_senhaTextActionPerformed

    private void appendnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendnSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appendnSelectActionPerformed

    private void usuarioText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioText1ActionPerformed

    }//GEN-LAST:event_usuarioText1ActionPerformed

    private void senhaText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaText1ActionPerformed

    }//GEN-LAST:event_senhaText1ActionPerformed

    private void appendnSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendnSelect1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appendnSelect1ActionPerformed

    private void metaimgSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metaimgSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metaimgSelectActionPerformed

    private void statusblockchainIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusblockchainIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusblockchainIntActionPerformed

    private void campowebserviceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campowebserviceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campowebserviceTextActionPerformed

    private void moduloentradaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloentradaBoxActionPerformed

        configBean.setModuloentradaBox(moduloentradaBox.getSelectedItem().toString());
    }//GEN-LAST:event_moduloentradaBoxActionPerformed

    private void modulosaidaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulosaidaBoxActionPerformed

        configBean.setModulosaidaBox(modulosaidaBox.getSelectedItem().toString());

    }//GEN-LAST:event_modulosaidaBoxActionPerformed

    private void moduloprocessoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloprocessoBoxActionPerformed

        configBean.setModuloprocessoBox(moduloprocessoBox.getSelectedItem().toString());
    }//GEN-LAST:event_moduloprocessoBoxActionPerformed

    private void idmoduloIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmoduloIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idmoduloIntActionPerformed

    private void urlsiarcoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlsiarcoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlsiarcoTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        PropertiesCsv propertiesCsv = new PropertiesCsv();

        if (usuarioText.getText() == null || usuarioText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar usuário !");
            return;

        } else {

            configBean.setUsuarioText(usuarioText.getText());
        }

        if (senhaText.getText() == null || senhaText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar senha !");
            return;

        } else {

            configBean.setSenhaText(senhaText.getText());
        }

        if (caminhologText.getText() == null || caminhologText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar caminho do log que será salvo !");
            return;

        } else {

            configBean.setCaminhologText(caminhologText.getText());

        }

        if (configdigitalizacaoText.getText() == null || configdigitalizacaoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar a config digitalização  !");
            return;

        } else {

            configBean.setConfigdigitalizacaoText(configdigitalizacaoText.getText());

        }

        if (urlwebserviceText.getText() == null || urlwebserviceText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar a url do webservice !");
            return;

        } else {

            configBean.setUrlwebserviceText(urlwebserviceText.getText());

        }

        if (statusblockchainInt.getText() == null || statusblockchainInt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o status do block chain  !");
            return;
        } else {

            configBean.setStatusblockchainInt(Integer.valueOf(statusblockchainInt.getText()));

        }

        if (campowebserviceText.getText() == null || campowebserviceText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar os campos do webservice  !");
            return;
        } else {

            configBean.setCampowebserviceText(campowebserviceText.getText());

        }

        if (appendsSelect.isSelected() == true) {

            configBean.setAppendsSelect(appendsSelect.isSelected());

        } else {

            configBean.setMetaSelect(metaSelect.isSelected());

        }

        if (metaSelect.isSelected() == true) {

            configBean.setMetaSelect(metaSelect.isSelected());

        } else {

            configBean.setMetaimgSelect(metaimgSelect.isSelected());

        }

        if (moduloentradaBox.getSelectedItem().equals("Selecione ...")) {

            //Selecione ..., CQ, Indexer, OCR, Content
            JOptionPane.showMessageDialog(null, "Selecione o modulo do entrada !");
            return;

        }

        if (modulosaidaBox.getSelectedItem().equals("Selecione ...")) {

            //Selecione ..., CQ, Indexer, OCR, Content
            JOptionPane.showMessageDialog(null, "Selecione o modulo de saida !");
            return;

        }

        if (moduloprocessoBox.getSelectedItem().equals("Selecione ...")) {

            //Selecione ..., CQ, Indexer, OCR, Content
            JOptionPane.showMessageDialog(null, "Selecione o modulo do processo !");
            return;

        }
        if (idmoduloInt.getText() == null || idmoduloInt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o ID modulo do processo  !");
            return;
        } else {

            configBean.setIdmoduloInt(Integer.valueOf(idmoduloInt.getText()));

        }

        if (siarcosSelect.isSelected() == true) {

            configBean.setSiarcosSelect(siarcosSelect.isSelected());

        } else {

            configBean.setSiarconSelect(siarconSelect.isSelected());

        }

        if (urlsiarcoText.getText() == null || urlsiarcoText.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Informar a url do webservice siarco  !");

        } else {

            configBean.setUrlsiarcoText(urlsiarcoText.getText());

        }
        ConfigBean configBean = null;

        strProperties = propertiesCsv.propetiesImportacaoCsv(configBean);

        if (strProperties != null) {

            propertiesCsv.expurgoArquivoProperties(strProperties, configBean);

        } else {

            JOptionPane.showMessageDialog(null, "Erro ao gerar properties !");
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton appendnSelect;
    private javax.swing.JRadioButton appendnSelect1;
    private javax.swing.JRadioButton appendsSelect;
    private javax.swing.JRadioButton appendsSelect1;
    private javax.swing.JTextField caminhologText;
    private javax.swing.JTextField caminhologText1;
    private javax.swing.JTextField campowebserviceText;
    private javax.swing.JTextField configdigitalizacaoText;
    private javax.swing.JTextField configdigitalizacaoText1;
    private javax.swing.JTextField idmoduloInt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton metaSelect;
    private javax.swing.JRadioButton metaimgSelect;
    private javax.swing.JComboBox moduloentradaBox;
    private javax.swing.JComboBox moduloprocessoBox;
    private javax.swing.JComboBox modulosaidaBox;
    private javax.swing.JTextField senhaText;
    private javax.swing.JTextField senhaText1;
    private javax.swing.JRadioButton siarconSelect;
    private javax.swing.JRadioButton siarcosSelect;
    private javax.swing.JTextField statusblockchainInt;
    private javax.swing.JTextField urlsiarcoText;
    private javax.swing.JTextField urlwebserviceText;
    private javax.swing.JTextField urlwebserviceText1;
    private javax.swing.JTextField usuarioText;
    private javax.swing.JTextField usuarioText1;
    // End of variables declaration//GEN-END:variables

}
