/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tci.importacao.view;

import javax.swing.JOptionPane;
import tci.importacao.bean.ConfigBean;
import tci.importacao.properties.PropertiesCsv;

/**
 *
 * @author erick.nagano
 */
public class ImportacaoImagemPasta extends javax.swing.JFrame {
    private ConfigBean configBean;
    private String strProperties;

    /**
     * Creates new form ImportacaoImagemPasta
     */
    public ImportacaoImagemPasta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioText = new javax.swing.JTextField();
        senhaText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caminhologText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        configdigitalizacaoText = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        urlwebserviceText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        appendsSelect = new javax.swing.JRadioButton();
        appendnSelect = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        metaSelect = new javax.swing.JRadioButton();
        metaimgSelect = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        nomecaixaText = new javax.swing.JTextField();
        nomeProcessoText = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nomeloteText1 = new javax.swing.JTextField();
        nomeDocumentoText = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        indiceImagem = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        statusblockchainInt = new javax.swing.JTextField();
        tipoprocessoText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tipodocumentoText = new javax.swing.JTextField();
        indicedocumentoText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        moduloentradaBox = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        modulosaidaBox = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        campowebserviceText = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        moduloprocessoBox = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        idmoduloInt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(38, 56, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 51, 204));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN WEBSERVICE CONTENT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário :");
        jLabel1.setToolTipText("Infome o usuário do Webservice");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        usuarioText.setBackground(new java.awt.Color(99, 99, 119));
        usuarioText.setForeground(new java.awt.Color(255, 255, 255));
        usuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextActionPerformed(evt);
            }
        });
        jPanel1.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, -1));

        senhaText.setBackground(new java.awt.Color(99, 99, 119));
        senhaText.setForeground(new java.awt.Color(255, 255, 255));
        senhaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextActionPerformed(evt);
            }
        });
        jPanel1.add(senhaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Caminho do arquivo LOG");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, -1));

        caminhologText.setBackground(new java.awt.Color(99, 99, 119));
        caminhologText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(caminhologText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 190, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome da ConfigDigitalizacao");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 260, -1));

        configdigitalizacaoText.setBackground(new java.awt.Color(99, 99, 119));
        configdigitalizacaoText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(configdigitalizacaoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 190, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("URL do Webservice");
        jLabel28.setToolTipText("");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, -1));

        urlwebserviceText.setBackground(new java.awt.Color(99, 99, 119));
        urlwebserviceText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(urlwebserviceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 190, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Append de arquivo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 230, -1));

        appendsSelect.setBackground(new java.awt.Color(38, 56, 74));
        appendsSelect.setForeground(new java.awt.Color(255, 255, 255));
        appendsSelect.setText("Sim");
        jPanel1.add(appendsSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        appendnSelect.setBackground(new java.awt.Color(38, 56, 74));
        appendnSelect.setForeground(new java.awt.Color(255, 255, 255));
        appendnSelect.setText("Não");
        appendnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendnSelectActionPerformed(evt);
            }
        });
        jPanel1.add(appendnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Metadados");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, -1));

        metaSelect.setBackground(new java.awt.Color(38, 56, 74));
        metaSelect.setForeground(new java.awt.Color(255, 255, 255));
        metaSelect.setText("Metadados");
        jPanel1.add(metaSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        metaimgSelect.setBackground(new java.awt.Color(38, 56, 74));
        metaimgSelect.setForeground(new java.awt.Color(255, 255, 255));
        metaimgSelect.setText("Metadados com imagem");
        metaimgSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metaimgSelectActionPerformed(evt);
            }
        });
        jPanel1.add(metaimgSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 180, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("DEFINIR NOME DO DOCUMENTO");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 220, 20));

        nomecaixaText.setBackground(new java.awt.Color(99, 99, 119));
        nomecaixaText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nomecaixaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, -1));

        nomeProcessoText.setBackground(new java.awt.Color(99, 99, 119));
        nomeProcessoText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nomeProcessoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 120, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Processo");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 100, 20));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Caixa");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Lote");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 40, 20));

        nomeloteText1.setBackground(new java.awt.Color(99, 99, 119));
        nomeloteText1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nomeloteText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 120, -1));

        nomeDocumentoText.setBackground(new java.awt.Color(99, 99, 119));
        nomeDocumentoText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nomeDocumentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 120, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Documento");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 60, -1));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Indice Imagem");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 90, 20));

        indiceImagem.setBackground(new java.awt.Color(99, 99, 119));
        indiceImagem.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(indiceImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 120, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Insere status na coluna blockChain");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 200, 20));

        statusblockchainInt.setBackground(new java.awt.Color(99, 99, 119));
        statusblockchainInt.setForeground(new java.awt.Color(255, 255, 255));
        statusblockchainInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusblockchainIntActionPerformed(evt);
            }
        });
        jPanel1.add(statusblockchainInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 320, 40, -1));

        tipoprocessoText.setBackground(new java.awt.Color(99, 99, 119));
        tipoprocessoText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tipoprocessoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 190, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nome do tipo processo : ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nome do tipo documento : ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 160, 20));

        tipodocumentoText.setBackground(new java.awt.Color(99, 99, 119));
        tipodocumentoText.setForeground(new java.awt.Color(255, 255, 255));
        tipodocumentoText.setToolTipText("Colocar separador entre os indices");
        jPanel1.add(tipodocumentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 190, -1));

        indicedocumentoText.setBackground(new java.awt.Color(99, 99, 119));
        indicedocumentoText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(indicedocumentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 190, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Indice do documento : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, 20));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Modulo de entrada");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, -1, 20));

        moduloentradaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Webcervice" }));
        moduloentradaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloentradaBoxActionPerformed(evt);
            }
        });
        jPanel1.add(moduloentradaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, 100, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Modulo de saida");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, -1, 20));

        modulosaidaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione ...", "CQ", "Indexer", "OCR", "Content" }));
        modulosaidaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulosaidaBoxActionPerformed(evt);
            }
        });
        jPanel1.add(modulosaidaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 100, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Campos do Webservice");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 280, -1));

        campowebserviceText.setBackground(new java.awt.Color(99, 99, 119));
        campowebserviceText.setForeground(new java.awt.Color(255, 255, 255));
        campowebserviceText.setToolTipText("Mais de um campo deverão ser separados por - \"traço\"");
        campowebserviceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campowebserviceTextActionPerformed(evt);
            }
        });
        jPanel1.add(campowebserviceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 190, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Modulo do processo");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, -1));

        moduloprocessoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione ...", "CQ", "Indexer", "OCR", "Content" }));
        moduloprocessoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloprocessoBoxActionPerformed(evt);
            }
        });
        jPanel1.add(moduloprocessoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 100, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ID Modulo do processo");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 200, 20));

        idmoduloInt.setBackground(new java.awt.Color(99, 99, 119));
        idmoduloInt.setForeground(new java.awt.Color(255, 255, 255));
        idmoduloInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmoduloIntActionPerformed(evt);
            }
        });
        jPanel1.add(idmoduloInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 100, -1));

        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed

    }//GEN-LAST:event_usuarioTextActionPerformed

    private void senhaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextActionPerformed

    }//GEN-LAST:event_senhaTextActionPerformed

    private void appendnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendnSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appendnSelectActionPerformed

    private void metaimgSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metaimgSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metaimgSelectActionPerformed

    private void statusblockchainIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusblockchainIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusblockchainIntActionPerformed

    private void moduloentradaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloentradaBoxActionPerformed

        configBean.setModuloentradaBox(moduloentradaBox.getSelectedItem().toString());
    }//GEN-LAST:event_moduloentradaBoxActionPerformed

    private void modulosaidaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulosaidaBoxActionPerformed

        configBean.setModulosaidaBox(modulosaidaBox.getSelectedItem().toString());

    }//GEN-LAST:event_modulosaidaBoxActionPerformed

    private void campowebserviceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campowebserviceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campowebserviceTextActionPerformed

    private void moduloprocessoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloprocessoBoxActionPerformed

        configBean.setModuloprocessoBox(moduloprocessoBox.getSelectedItem().toString());
    }//GEN-LAST:event_moduloprocessoBoxActionPerformed

    private void idmoduloIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmoduloIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idmoduloIntActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        PropertiesCsv propertiesCsv = new PropertiesCsv();

        if (usuarioText.getText() == null || usuarioText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar usuário !");
            return;

        } else {

            configBean.setUsuarioText(usuarioText.getText());
        }

        if (senhaText.getText() == null || senhaText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar senha !");
            return;

        } else {

            configBean.setSenhaText(senhaText.getText());
        }

        if (caminhologText.getText() == null || caminhologText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar caminho do log que será salvo !");
            return;

        } else {

            configBean.setCaminhologText(caminhologText.getText());

        }

        if (configdigitalizacaoText.getText() == null || configdigitalizacaoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar a config digitalização  !");
            return;

        } else {

            configBean.setConfigdigitalizacaoText(configdigitalizacaoText.getText());

        }

        if (urlwebserviceText.getText() == null || urlwebserviceText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar a url do webservice !");
            return;

        } else {

            configBean.setUrlwebserviceText(urlwebserviceText.getText());

        }

        if (tipoprocessoText.getText() == null || tipoprocessoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o tipo de processo !");
            return;
        } else {

            configBean.setTipoprocessoText(tipoprocessoText.getText());

        }

        if (tipodocumentoText.getText() == null || tipodocumentoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o tipo documento !");
            return;
        } else {

            configBean.setTipodocumentoText(tipodocumentoText.getText());

        }

        if (nomecaixaText.getText() == null || nomecaixaText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o nome da caixa !");
            return;
        } else {

            configBean.setNomecaixaText(nomecaixaText.getText());

        }

        if (nomeProcessoText.getText() == null || nomeProcessoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o nome protocolo !");
            return;
        } else {

            configBean.setNomeProcessoText(nomeProcessoText.getText());

        }

        if (nomeDocumentoText.getText() == null || nomeDocumentoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o nome do lote !");
            return;
        } else {

            configBean.setNomeloteText(nomeDocumentoText.getText());

        }

        if (statusblockchainInt.getText() == null || statusblockchainInt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o status do block chain  !");
            return;
        } else {

            configBean.setStatusblockchainInt(Integer.valueOf(statusblockchainInt.getText()));

        }

        if (campowebserviceText.getText() == null || campowebserviceText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar os campos do webservice  !");
            return;
        } else {

            configBean.setCampowebserviceText(campowebserviceText.getText());

        }

        if (appendsSelect.isSelected() == true) {

            configBean.setAppendsSelect(appendsSelect.isSelected());

        } else {

            configBean.setMetaSelect(metaSelect.isSelected());

        }

        if (metaSelect.isSelected() == true) {

            configBean.setMetaSelect(metaSelect.isSelected());

        } else {

            configBean.setMetaimgSelect(metaimgSelect.isSelected());

        }

        if (moduloentradaBox.getSelectedItem().equals("Selecione ...")) {

            //Selecione ..., CQ, Indexer, OCR, Content
            JOptionPane.showMessageDialog(null, "Selecione o modulo do entrada !");
            return;

        }

        if (modulosaidaBox.getSelectedItem().equals("Selecione ...")) {

            //Selecione ..., CQ, Indexer, OCR, Content
            JOptionPane.showMessageDialog(null, "Selecione o modulo de saida !");
            return;

        }

        if (moduloprocessoBox.getSelectedItem().equals("Selecione ...")) {

            //Selecione ..., CQ, Indexer, OCR, Content
            JOptionPane.showMessageDialog(null, "Selecione o modulo do processo !");
            return;

        }
        if (idmoduloInt.getText() == null || idmoduloInt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informar o ID modulo do processo  !");
            return;
        } else {

            configBean.setIdmoduloInt(Integer.valueOf(idmoduloInt.getText()));

        }

        strProperties = propertiesCsv.propetiesImportacaoCsv(configBean);

        if (!strProperties.equals(null)) {

            propertiesCsv.expurgoArquivoProperties(strProperties, configBean);

        } else {

            JOptionPane.showMessageDialog(null, "Erro ao gerar properties !");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton appendnSelect;
    private javax.swing.JRadioButton appendsSelect;
    private javax.swing.JTextField caminhologText;
    private javax.swing.JTextField campowebserviceText;
    private javax.swing.JTextField configdigitalizacaoText;
    private javax.swing.JTextField idmoduloInt;
    private javax.swing.JTextField indiceImagem;
    private javax.swing.JTextField indicedocumentoText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton metaSelect;
    private javax.swing.JRadioButton metaimgSelect;
    private javax.swing.JComboBox moduloentradaBox;
    private javax.swing.JComboBox moduloprocessoBox;
    private javax.swing.JComboBox modulosaidaBox;
    private javax.swing.JTextField nomeDocumentoText;
    private javax.swing.JTextField nomeProcessoText;
    private javax.swing.JTextField nomecaixaText;
    private javax.swing.JTextField nomeloteText1;
    private javax.swing.JTextField senhaText;
    private javax.swing.JTextField statusblockchainInt;
    private javax.swing.JTextField tipodocumentoText;
    private javax.swing.JTextField tipoprocessoText;
    private javax.swing.JTextField urlwebserviceText;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
